const RuralData = {
  meta: {
    appName: "乡行共创",
    version: "v1-rural-culture-ai",
    updatedAt: "2026-06-28",
    note:
      "原型数据用于网页设计与比赛演示。全国乡村旅游重点村镇数量、政策与行业趋势来自公开资料；村镇体验时长、预算、承载、增收估算为产品逻辑演示值，正式落地需接入当地文旅局、地图与经营主体数据。",
  },

  heroImage:
    "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=82",

  personas: [
    {
      id: "student",
      name: "大学生研学",
      icon: "graduation-cap",
      days: 3,
      budget: 980,
      pace: "balanced",
      description: "预算敏感，重视田野调研、非遗体验、可写进实践报告的社会价值。",
      preferences: ["fieldwork", "craft", "heritage"],
    },
    {
      id: "family",
      name: "亲子农事",
      icon: "baby",
      days: 2,
      budget: 1280,
      pace: "slow",
      description: "需要安全、轻体力、动手体验和清晰休息节点。",
      preferences: ["farming", "food", "nature"],
    },
    {
      id: "slow",
      name: "乡居慢游",
      icon: "house",
      days: 4,
      budget: 1880,
      pace: "slow",
      description: "少打卡，多停留，适合民宿旅居、村落散步和地方饮食体验。",
      preferences: ["homestay", "food", "heritage"],
    },
    {
      id: "research",
      name: "产业调研",
      icon: "clipboard-list",
      days: 3,
      budget: 1380,
      pace: "compact",
      description: "关注乡村运营、资源盘活、特产供应链和村民增收模型。",
      preferences: ["resource", "commerce", "fieldwork"],
    },
  ],

  experienceTags: [
    { id: "farming", name: "农事体验", icon: "wheat", color: "#7C9B42" },
    { id: "craft", name: "非遗手作", icon: "scissors", color: "#B76646" },
    { id: "heritage", name: "古村民俗", icon: "landmark", color: "#7E6A9E" },
    { id: "food", name: "乡土风味", icon: "utensils", color: "#B58936" },
    { id: "nature", name: "山野徒步", icon: "trees", color: "#3F8273" },
    { id: "homestay", name: "民宿旅居", icon: "bed", color: "#5077A7" },
    { id: "fieldwork", name: "田野调研", icon: "notebook-pen", color: "#5C6F82" },
    { id: "commerce", name: "特产助农", icon: "shopping-bag", color: "#A64B5F" },
    { id: "resource", name: "资源盘活", icon: "warehouse", color: "#7D724C" },
  ],

  villages: [
    {
      id: "xidi",
      name: "西递村",
      province: "安徽",
      city: "黄山市黟县",
      label: "徽派古村研学样板",
      cover:
        "https://images.unsplash.com/photo-1586358070553-2a082dc63e1f?auto=format&fit=crop&w=1300&q=82",
      fallbackVisual: "徽派马头墙、宗祠、水口、村落肌理",
      lat: 29.904,
      lng: 117.994,
      bestSeason: "春秋写生、暑期研学",
      matchScore: 94,
      capacity: "中",
      stayNights: 1,
      tags: ["heritage", "fieldwork", "food", "homestay"],
      highlights: ["徽派建筑测绘", "家风家训访谈", "徽州小吃体验", "村落保护议题"],
      painPoints: ["旺季客流集中", "研学内容容易停留在参观层面", "夜间消费场景单一"],
      resources: ["老宅讲解员", "徽州点心工坊", "闲置院落", "写生点位"],
      products: ["黄山烧饼", "徽墨文创", "黟县腊八豆腐"],
      sourceType: "全国乡村旅游重点村名录 / 公开资料原型化整理",
    },
    {
      id: "azheke",
      name: "阿者科村",
      province: "云南",
      city: "红河州元阳县",
      label: "哈尼梯田共益旅游",
      cover:
        "https://images.unsplash.com/photo-1563969072881-b0fc7f3d77d7?auto=format&fit=crop&w=1300&q=82",
      fallbackVisual: "梯田、蘑菇房、哈尼节庆、村民共益机制",
      lat: 23.096,
      lng: 102.744,
      bestSeason: "11月至次年4月梯田观景",
      matchScore: 96,
      capacity: "低",
      stayNights: 2,
      tags: ["farming", "heritage", "fieldwork", "nature"],
      highlights: ["梯田灌溉系统观察", "蘑菇房村落导览", "共益旅游案例访谈", "稻作文化课程"],
      painPoints: ["山地交通耗时", "天气影响梯田可视性", "接待容量需要控制"],
      resources: ["梯田导览员", "传统民居", "稻作体验田", "民族餐食"],
      products: ["红米", "梯田鸭蛋", "哈尼刺绣"],
      sourceType: "UN Tourism最佳旅游乡村 / 公开资料原型化整理",
    },
    {
      id: "shibadong",
      name: "十八洞村",
      province: "湖南",
      city: "湘西州花垣县",
      label: "精准帮扶与苗寨文旅",
      cover:
        "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1300&q=82",
      fallbackVisual: "苗寨、峡谷、非遗银饰、乡村治理展陈",
      lat: 28.395,
      lng: 109.497,
      bestSeason: "春夏苗寨活动、秋季山地徒步",
      matchScore: 91,
      capacity: "中",
      stayNights: 1,
      tags: ["heritage", "craft", "fieldwork", "commerce"],
      highlights: ["乡村振兴案例研学", "苗绣银饰体验", "山地村落徒步", "特产助农展销"],
      painPoints: ["研学叙事需避免口号化", "手作体验预约分散", "周边交通衔接复杂"],
      resources: ["苗绣工坊", "村史展馆", "山地步道", "农产品合作社"],
      products: ["苗绣包", "猕猴桃", "湘西腊肉"],
      sourceType: "乡村振兴案例 / 公开资料原型化整理",
    },
    {
      id: "beigou",
      name: "北沟村",
      province: "北京",
      city: "怀柔区渤海镇",
      label: "长城脚下民宿集群",
      cover:
        "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1300&q=82",
      fallbackVisual: "长城、民宿院落、乡村咖啡、近郊度假",
      lat: 40.432,
      lng: 116.58,
      bestSeason: "周末近郊、秋季长城徒步",
      matchScore: 88,
      capacity: "高",
      stayNights: 1,
      tags: ["homestay", "nature", "food", "commerce"],
      highlights: ["长城生态徒步", "民宿运营访谈", "乡村咖啡消费观察", "近郊微度假模型"],
      painPoints: ["周末价格波动", "体验容易变成单一住宿", "自驾依赖较强"],
      resources: ["精品民宿", "长城步道", "村民餐厅", "庭院空间"],
      products: ["板栗", "怀柔虹鳟鱼", "乡村咖啡"],
      sourceType: "全国乡村旅游重点村名录 / 公开资料原型化整理",
    },
    {
      id: "yucun",
      name: "余村",
      province: "浙江",
      city: "湖州市安吉县",
      label: "生态转型与竹产业",
      cover:
        "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=1300&q=82",
      fallbackVisual: "竹林、生态展示馆、绿道、乡村运营",
      lat: 30.624,
      lng: 119.699,
      bestSeason: "全年生态研学、春夏竹林体验",
      matchScore: 93,
      capacity: "高",
      stayNights: 1,
      tags: ["nature", "craft", "fieldwork", "resource"],
      highlights: ["生态文明研学", "竹编工坊体验", "绿道骑行", "闲置资源再运营观察"],
      painPoints: ["热门研学团集中", "深度体验需要提前预约", "单日停留消费转化不足"],
      resources: ["竹编工坊", "生态展馆", "绿道驿站", "乡创空间"],
      products: ["安吉白茶", "竹编器物", "笋干"],
      sourceType: "生态文明乡村案例 / 公开资料原型化整理",
    },
    {
      id: "xiaogang",
      name: "小岗村",
      province: "安徽",
      city: "滁州市凤阳县",
      label: "改革记忆与农业研学",
      cover:
        "https://images.unsplash.com/photo-1499529112087-3cb3b73cec95?auto=format&fit=crop&w=1300&q=82",
      fallbackVisual: "农田、村史馆、粮食作物、农业合作社",
      lat: 32.852,
      lng: 117.566,
      bestSeason: "春耕秋收、红色研学",
      matchScore: 89,
      capacity: "中",
      stayNights: 1,
      tags: ["farming", "fieldwork", "heritage", "commerce"],
      highlights: ["村史馆研学", "田块认养体验", "农业合作社访谈", "农产品供应链观察"],
      painPoints: ["体验产品需要更年轻化", "住宿与夜间活动需补强", "农事受季节影响明显"],
      resources: ["村史馆", "认养农田", "合作社", "农产品展销点"],
      products: ["小岗大米", "黑豆制品", "粮食文创"],
      sourceType: "UN Tourism最佳旅游乡村 / 公开资料原型化整理",
    },
  ],

  resourceAssets: [
    {
      id: "yard-xidi",
      type: "闲置院落",
      villageId: "xidi",
      title: "徽州老宅半日研学空间",
      owner: "村集体合作社",
      currentState: "淡季空置",
      fit: ["fieldwork", "heritage", "food"],
      estimateIncome: 1800,
      risk: "需控制噪音与古建承载",
      action: "适合改造成家风访谈、徽州点心课和写生补给点。",
    },
    {
      id: "field-azheke",
      type: "农事田块",
      villageId: "azheke",
      title: "梯田稻作观察田",
      owner: "村民小组",
      currentState: "季节性开放",
      fit: ["farming", "fieldwork", "nature"],
      estimateIncome: 2600,
      risk: "雨季安全与田埂保护",
      action: "适合预约制小班研学，结合梯田水系讲解和红米溯源。",
    },
    {
      id: "craft-yucun",
      type: "非遗工坊",
      villageId: "yucun",
      title: "竹编体验工坊空档时段",
      owner: "乡创团队",
      currentState: "工作日利用率低",
      fit: ["craft", "fieldwork", "commerce"],
      estimateIncome: 1450,
      risk: "手作老师排班不稳定",
      action: "适合大学生实践队工作日预约，产出可转为助农文创。",
    },
    {
      id: "homestay-beigou",
      type: "民宿余房",
      villageId: "beigou",
      title: "长城民宿周中余房",
      owner: "民宿经营户",
      currentState: "周中入住率偏低",
      fit: ["homestay", "nature", "food"],
      estimateIncome: 3200,
      risk: "周末价格波动明显",
      action: "适合设计周中研学团和慢游包价，带动餐饮与采摘。",
    },
    {
      id: "coop-xiaogang",
      type: "合作社展销",
      villageId: "xiaogang",
      title: "农产品合作社展销角",
      owner: "农产品合作社",
      currentState: "游客转化弱",
      fit: ["commerce", "farming", "fieldwork"],
      estimateIncome: 2100,
      risk: "产品故事化不足",
      action: "适合接入路线结尾的溯源购买和实践队直播展销。",
    },
  ],

  evidence: [
    {
      id: "mct-villages",
      title: "全国乡村旅游重点村镇名录",
      value: "四批1399个重点村、198个重点镇",
      source: "文化和旅游部",
      url: "https://www.mct.gov.cn/whzx/whyw/202311/t20231127_949963.htm",
      use: "作为村镇库与政策立意依据，避免做全国城市旅游的大而全。",
    },
    {
      id: "mct-data-service",
      title: "文化和旅游部数据服务栏目",
      value: "可查询全国乡村旅游重点村",
      source: "文化和旅游部数据服务",
      url: "https://sjfw.mct.gov.cn/site/dataservice/rural",
      use: "后续可扩展为按省份抓取重点村清单与基础信息。",
    },
    {
      id: "mct-2024-market",
      title: "2024年前三季度乡村旅游监测",
      value: "22.48亿人次、1.32万亿元",
      source: "证券时报转述文化和旅游部数据",
      url: "https://stcn.com/article/detail/1414176.html",
      use: "用于说明乡村文旅市场规模与增长背景。",
    },
    {
      id: "ctrip-2023",
      title: "携程集团乡村旅游振兴白皮书",
      value: "2023年前三季度乡村旅游订单量恢复至2019年同期264%",
      source: "携程集团白皮书",
      url: "https://pages.c-ctrip.com/commerce/promote/201201/other/qygm/qygm2023bps-1.pdf",
      use: "用于支撑年轻客群、民宿供给、农事体验等产品设计。",
    },
    {
      id: "ctrip-2024",
      title: "2024乡村旅游振兴白皮书公开报道",
      value: "乡村旅游订单同比提升10%，乡村民宿订单同比增长近24.3%",
      source: "新京报贝壳财经",
      url: "https://m.bjnews.com.cn/detail/1735549688168951.html",
      use: "用于说明乡村游和民宿供给持续增长。",
    },
  ],

  marketStats: [
    { label: "重点村", value: 1399, unit: "个", tone: "green" },
    { label: "重点镇", value: 198, unit: "个", tone: "gold" },
    { label: "前三季度接待", value: 22.48, unit: "亿人次", tone: "blue" },
    { label: "前三季度收入", value: 1.32, unit: "万亿元", tone: "rose" },
  ],
};

const ExistingVillageSpots = {
  xidi: [
    {
      id: "xidi-hu-wenguang",
      name: "胡文光刺史牌坊与村口水口",
      type: "古村导览",
      duration: "50分钟",
      price: 35,
      bookingRequired: false,
      tags: ["heritage", "fieldwork"],
      bestTime: "09:00-10:30",
      desc: "从村口空间、宗族叙事和游客动线切入，适合做徽州古村第一站观察。",
    },
    {
      id: "xidi-jingai-hall",
      name: "敬爱堂家风访谈课",
      type: "研学访谈",
      duration: "1小时",
      price: 60,
      bookingRequired: true,
      tags: ["heritage", "fieldwork"],
      bestTime: "10:30-11:30",
      desc: "围绕祠堂、家训和村落公共生活设计访谈提纲，避免只看建筑不理解乡土社会。",
    },
    {
      id: "xidi-huizhou-snack",
      name: "徽州点心与黄山烧饼体验",
      type: "乡土风味",
      duration: "1.5小时",
      price: 88,
      bookingRequired: true,
      tags: ["food", "commerce"],
      bestTime: "14:00-16:00",
      desc: "把地方小吃制作、伴手礼包装和消费转化放进行程，适合亲子与学生团队。",
    },
    {
      id: "xidi-sketch-lane",
      name: "明清街巷写生与影像采集",
      type: "写生摄影",
      duration: "2小时",
      price: 40,
      bookingRequired: false,
      tags: ["heritage", "nature"],
      bestTime: "15:00-17:30",
      desc: "选择巷道、马头墙和水系节点做轻量写生与摄影任务，补足乡村图片素材。",
    },
    {
      id: "xidi-old-yard",
      name: "闲置老宅微展陈共创",
      type: "资源盘活",
      duration: "2小时",
      price: 120,
      bookingRequired: true,
      tags: ["resource", "fieldwork", "craft"],
      bestTime: "工作日全天",
      desc: "把闲置院落变成调研展示和手作课程空间，用小班预约提升淡季利用率。",
    },
  ],
  azheke: [
    {
      id: "azheke-terrace-water",
      name: "哈尼梯田水系观察线",
      type: "生态研学",
      duration: "2小时",
      price: 80,
      bookingRequired: true,
      tags: ["farming", "nature", "fieldwork"],
      bestTime: "日出后至10:30",
      desc: "观察森林、村寨、梯田、水系的关系，适合做生态农业与共同体议题。",
    },
    {
      id: "azheke-mushroom-house",
      name: "蘑菇房村落导览",
      type: "民居导览",
      duration: "1小时",
      price: 50,
      bookingRequired: true,
      tags: ["heritage", "fieldwork"],
      bestTime: "10:30-12:00",
      desc: "讲清传统民居、聚落格局与旅游接待边界，帮助游客理解为什么要控制容量。",
    },
    {
      id: "azheke-red-rice",
      name: "红米溯源与稻作体验",
      type: "农事体验",
      duration: "2小时",
      price: 96,
      bookingRequired: true,
      tags: ["farming", "commerce", "food"],
      bestTime: "14:00-16:30",
      desc: "按季节安排插秧、收割、晒谷或红米品鉴，把农产品变成可讲述的体验。",
    },
    {
      id: "azheke-benefit-talk",
      name: "共益旅游机制访谈",
      type: "产业调研",
      duration: "1.5小时",
      price: 70,
      bookingRequired: true,
      tags: ["fieldwork", "resource"],
      bestTime: "16:00-17:30",
      desc: "访谈合作社、讲解员或村民代表，理解收益分配和社区参与。",
    },
    {
      id: "azheke-evening-fire",
      name: "哈尼家宴与夜间故事会",
      type: "夜间体验",
      duration: "2小时",
      price: 138,
      bookingRequired: true,
      tags: ["food", "homestay", "heritage"],
      bestTime: "18:30-20:30",
      desc: "把住宿夜晚转为餐食、歌舞、口述故事和调研复盘的复合消费节点。",
    },
  ],
  shibadong: [
    {
      id: "shibadong-village-history",
      name: "十八洞村史与振兴案例馆",
      type: "主题研学",
      duration: "1.5小时",
      price: 50,
      bookingRequired: true,
      tags: ["heritage", "fieldwork"],
      bestTime: "09:30-11:00",
      desc: "把政策叙事转化为村民生活、产业变化和游客感知三个观察维度。",
    },
    {
      id: "shibadong-miao-embroidery",
      name: "苗绣图案采集与手作",
      type: "非遗手作",
      duration: "2小时",
      price: 118,
      bookingRequired: true,
      tags: ["craft", "commerce"],
      bestTime: "14:00-16:00",
      desc: "由绣娘带领完成小件手作，结尾接入文创购买和线上传播素材。",
    },
    {
      id: "shibadong-silver-talk",
      name: "苗银纹样与佩饰故事",
      type: "民俗体验",
      duration: "1小时",
      price: 68,
      bookingRequired: true,
      tags: ["craft", "heritage"],
      bestTime: "10:30-11:30",
      desc: "通过银饰纹样、节庆佩戴和家庭记忆讲清苗寨文化符号。",
    },
    {
      id: "shibadong-canyon-walk",
      name: "山地峡谷轻徒步",
      type: "山野徒步",
      duration: "2.5小时",
      price: 90,
      bookingRequired: true,
      tags: ["nature", "fieldwork"],
      bestTime: "08:30-11:30",
      desc: "以安全路线连接村寨、山地作物和景观节点，适合低强度团队。",
    },
    {
      id: "shibadong-kiwi-coop",
      name: "猕猴桃合作社助农直播点",
      type: "助农展销",
      duration: "1小时",
      price: 45,
      bookingRequired: false,
      tags: ["commerce", "resource", "farming"],
      bestTime: "16:30-17:30",
      desc: "把特产从陈列货架升级为溯源、试吃、直播和团购转化。",
    },
  ],
  beigou: [
    {
      id: "beigou-greatwall-walk",
      name: "长城脚下生态步道",
      type: "山野徒步",
      duration: "2小时",
      price: 60,
      bookingRequired: false,
      tags: ["nature", "fieldwork"],
      bestTime: "08:00-10:30",
      desc: "把近郊徒步和村落生态修复连接起来，适合周末轻旅行。",
    },
    {
      id: "beigou-homestay-ops",
      name: "民宿运营访谈课",
      type: "产业调研",
      duration: "1.5小时",
      price: 120,
      bookingRequired: true,
      tags: ["homestay", "fieldwork", "resource"],
      bestTime: "工作日14:00-16:00",
      desc: "访谈民宿主，理解定价、淡旺季、客群和村民参与。",
    },
    {
      id: "beigou-yard-cafe",
      name: "乡村咖啡与庭院市集",
      type: "乡村消费",
      duration: "1小时",
      price: 58,
      bookingRequired: false,
      tags: ["food", "commerce"],
      bestTime: "15:00-17:00",
      desc: "让游客停留在村内消费，而不是只把村庄当作长城住宿点。",
    },
    {
      id: "beigou-rainbow-trout",
      name: "虹鳟鱼乡味晚餐",
      type: "乡土风味",
      duration: "1.5小时",
      price: 128,
      bookingRequired: true,
      tags: ["food", "homestay"],
      bestTime: "18:00-19:30",
      desc: "把怀柔餐食做成可预订的晚间体验，补齐周中客源转化。",
    },
    {
      id: "beigou-chestnut-pick",
      name: "板栗采摘与烘焙",
      type: "农事体验",
      duration: "2小时",
      price: 88,
      bookingRequired: true,
      tags: ["farming", "food", "commerce"],
      bestTime: "9月至10月",
      desc: "季节性强，适合家庭和公司团建，结尾可设计伴手礼。",
    },
  ],
  yucun: [
    {
      id: "yucun-ecology-hall",
      name: "生态转型主题馆",
      type: "主题研学",
      duration: "1.5小时",
      price: 45,
      bookingRequired: true,
      tags: ["fieldwork", "heritage"],
      bestTime: "09:30-11:00",
      desc: "从矿山转型、村庄治理和生态产业三个角度讲清余村样本。",
    },
    {
      id: "yucun-bamboo-workshop",
      name: "竹编工坊小班课",
      type: "非遗手作",
      duration: "2小时",
      price: 118,
      bookingRequired: true,
      tags: ["craft", "commerce"],
      bestTime: "14:00-16:00",
      desc: "把竹产业文化、手作体验和文创售卖连成一个闭环。",
    },
    {
      id: "yucun-greenway-bike",
      name: "竹林绿道骑行",
      type: "生态骑行",
      duration: "2小时",
      price: 70,
      bookingRequired: false,
      tags: ["nature", "homestay"],
      bestTime: "16:00-18:00",
      desc: "用绿道串联竹林、乡创空间和民宿，提升慢游停留感。",
    },
    {
      id: "yucun-white-tea",
      name: "安吉白茶品鉴与溯源",
      type: "乡土风味",
      duration: "1小时",
      price: 88,
      bookingRequired: true,
      tags: ["food", "commerce", "farming"],
      bestTime: "春茶季或下午",
      desc: "将茶园、制茶、品饮和购买连接，适合中老年和研学客群。",
    },
    {
      id: "yucun-idle-space",
      name: "乡创空间资源盘活会",
      type: "资源盘活",
      duration: "1.5小时",
      price: 80,
      bookingRequired: true,
      tags: ["resource", "fieldwork"],
      bestTime: "工作日",
      desc: "面向运营者梳理闲置空间、活动排期和收益模型。",
    },
  ],
  xiaogang: [
    {
      id: "xiaogang-reform-memorial",
      name: "小岗村改革记忆馆",
      type: "主题研学",
      duration: "1.5小时",
      price: 45,
      bookingRequired: true,
      tags: ["heritage", "fieldwork"],
      bestTime: "09:30-11:00",
      desc: "把历史事件、家庭承包责任制和当代乡村产业联系起来。",
    },
    {
      id: "xiaogang-field-adopt",
      name: "田块认养与作物观察",
      type: "农事体验",
      duration: "2小时",
      price: 88,
      bookingRequired: true,
      tags: ["farming", "fieldwork"],
      bestTime: "春耕秋收",
      desc: "适合长期研学和亲子复访，形成从一次游到持续认养的关系。",
    },
    {
      id: "xiaogang-coop-talk",
      name: "农业合作社供应链访谈",
      type: "产业调研",
      duration: "1.5小时",
      price: 70,
      bookingRequired: true,
      tags: ["commerce", "resource", "fieldwork"],
      bestTime: "14:00-15:30",
      desc: "关注产品标准、包装、渠道和游客转化，适合产业调研客群。",
    },
    {
      id: "xiaogang-grain-kitchen",
      name: "五谷厨房与乡味午餐",
      type: "乡土风味",
      duration: "1.5小时",
      price: 98,
      bookingRequired: true,
      tags: ["food", "farming"],
      bestTime: "11:30-13:00",
      desc: "把大米、黑豆和地方菜做成可预订餐食，增强村内消费。",
    },
    {
      id: "xiaogang-night-class",
      name: "村民夜校与调研复盘",
      type: "夜间体验",
      duration: "1.5小时",
      price: 55,
      bookingRequired: true,
      tags: ["homestay", "fieldwork"],
      bestTime: "19:30-21:00",
      desc: "为研学团队保留夜间讨论和访谈节点，提升住宿必要性。",
    },
  ],
};

const AdditionalVillages = [
  {
    id: "hongcun",
    name: "宏村",
    province: "安徽",
    city: "黄山市黟县",
    label: "水系古村与写生旅居",
    cover: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "月沼、南湖、徽派民居、写生人群、夜游水系",
    lat: 30.008,
    lng: 117.987,
    bestSeason: "春秋写生、夏季夜游",
    matchScore: 95,
    capacity: "高",
    stayNights: 1,
    tags: ["heritage", "food", "homestay", "fieldwork"],
    highlights: ["水系古村导览", "艺术写生", "徽州餐食", "民宿旅居"],
    painPoints: ["核心景点拥挤", "停留同质化", "夜间内容需分层"],
    resources: ["写生基地", "老宅民宿", "徽菜餐厅", "夜游点位"],
    products: ["徽州毛豆腐", "烧饼礼盒", "写生文创"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "hongcun-moon-pond", name: "月沼水系讲解", type: "古村导览", duration: "45分钟", price: 35, bookingRequired: false, tags: ["heritage", "fieldwork"], bestTime: "08:30-10:00", desc: "从水系、宗族和公共空间理解古村肌理。" },
      { id: "hongcun-south-lake", name: "南湖晨景写生", type: "写生摄影", duration: "2小时", price: 40, bookingRequired: false, tags: ["heritage", "nature"], bestTime: "07:00-09:30", desc: "适合学生写生、摄影采集和慢游停留。" },
      { id: "hongcun-huizhou-food", name: "徽州毛豆腐餐桌课", type: "乡土风味", duration: "1.5小时", price: 96, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "把餐食变成地方饮食文化和伴手礼转化。" },
      { id: "hongcun-night-water", name: "古村夜游与民宿茶叙", type: "夜间体验", duration: "1.5小时", price: 80, bookingRequired: true, tags: ["homestay", "heritage"], bestTime: "19:30-21:00", desc: "补足古村夜间内容，适合住客深度游。" },
      { id: "hongcun-yard-class", name: "老宅院落微课堂", type: "资源盘活", duration: "1.5小时", price: 90, bookingRequired: true, tags: ["resource", "fieldwork"], bestTime: "工作日", desc: "将院落空档做成小型研学、展陈和分享空间。" },
    ],
  },
  {
    id: "huangling",
    name: "篁岭村",
    province: "江西",
    city: "上饶市婺源县",
    label: "晒秋景观与山居体验",
    cover: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "晒秋、梯田、徽派民居、油菜花、山居索道",
    lat: 29.357,
    lng: 118.117,
    bestSeason: "春季花海、秋季晒秋",
    matchScore: 92,
    capacity: "高",
    stayNights: 1,
    tags: ["heritage", "food", "nature", "commerce"],
    highlights: ["晒秋民俗", "梯田花海", "乡土风味", "山地夜游"],
    painPoints: ["网红打卡拥挤", "客流季节波动", "村民参与需细化"],
    resources: ["晒秋平台", "梯田步道", "乡味餐厅", "民俗展陈"],
    products: ["婺源皇菊", "米酒", "辣椒酱"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "huangling-sun-drying", name: "晒秋工坊与晒盘布置", type: "民俗体验", duration: "1.5小时", price: 98, bookingRequired: true, tags: ["heritage", "craft"], bestTime: "09:00-11:00", desc: "理解晒秋从生产习俗到景观产品的转化。" },
      { id: "huangling-terrace-flower", name: "梯田花海步道", type: "山野徒步", duration: "2小时", price: 60, bookingRequired: false, tags: ["nature", "fieldwork"], bestTime: "春季上午", desc: "将油菜花、村落视线和步道安全纳入路线。" },
      { id: "huangling-spice-kitchen", name: "辣椒酱与米酒小课", type: "乡土风味", duration: "1小时", price: 78, bookingRequired: true, tags: ["food", "commerce"], bestTime: "15:00-16:30", desc: "适合做成游客能带走的地方味道。" },
      { id: "huangling-photo-route", name: "晒秋摄影路线", type: "摄影采集", duration: "1.5小时", price: 45, bookingRequired: false, tags: ["heritage", "nature"], bestTime: "16:00-17:30", desc: "为平台图片素材和游客社交传播提供稳定点位。" },
      { id: "huangling-night-market", name: "山居夜市与特产转化", type: "助农展销", duration: "1.5小时", price: 40, bookingRequired: false, tags: ["commerce", "food"], bestTime: "19:00-20:30", desc: "把夜间客流导入餐饮、特产和小型表演。" },
    ],
  },
  {
    id: "longji-pingan",
    name: "平安壮寨",
    province: "广西",
    city: "桂林市龙胜县",
    label: "龙脊梯田与壮族山居",
    cover: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "龙脊梯田、吊脚楼、壮族服饰、山地稻作",
    lat: 25.764,
    lng: 110.116,
    bestSeason: "5月至10月梯田季",
    matchScore: 91,
    capacity: "中",
    stayNights: 2,
    tags: ["farming", "nature", "food", "homestay"],
    highlights: ["梯田徒步", "壮族饮食", "山居民宿", "稻作体验"],
    painPoints: ["雨雾影响观景", "山路体力要求", "民宿品质差异"],
    resources: ["梯田观景台", "山居民宿", "稻作田块", "民族餐食"],
    products: ["龙脊辣椒", "竹筒饭", "梯田米"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "longji-nine-dragon", name: "九龙五虎观景线", type: "山野徒步", duration: "2.5小时", price: 75, bookingRequired: false, tags: ["nature", "fieldwork"], bestTime: "07:30-10:30", desc: "连接观景台和村寨，适合做地形、交通和游客承载观察。" },
      { id: "longji-rice-work", name: "梯田农事半日课", type: "农事体验", duration: "2小时", price: 108, bookingRequired: true, tags: ["farming", "nature"], bestTime: "插秧或收割季", desc: "按季节安排插秧、割稻、晒谷或田埂维护。" },
      { id: "longji-bamboo-rice", name: "竹筒饭与山泉茶", type: "乡土风味", duration: "1.5小时", price: 92, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "把山居午餐做成可体验、可复购的餐食产品。" },
      { id: "longji-zhuang-dress", name: "壮族服饰纹样体验", type: "民俗手作", duration: "1小时", price: 68, bookingRequired: true, tags: ["heritage", "craft"], bestTime: "14:30-16:00", desc: "通过服饰纹样讲述民族文化和家庭记忆。" },
      { id: "longji-homestay-dawn", name: "山居民宿日出早餐", type: "民宿旅居", duration: "1小时", price: 80, bookingRequired: true, tags: ["homestay", "food"], bestTime: "日出前后", desc: "提升过夜价值，避免游客只做一日打卡。" },
    ],
  },
  {
    id: "zhaoxing",
    name: "肇兴侗寨",
    province: "贵州",
    city: "黔东南州黎平县",
    label: "侗族鼓楼与大歌体验",
    cover: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "鼓楼、风雨桥、侗族大歌、蓝染、稻田",
    lat: 25.913,
    lng: 109.181,
    bestSeason: "春秋民俗、夏季稻田",
    matchScore: 94,
    capacity: "中",
    stayNights: 2,
    tags: ["heritage", "craft", "food", "homestay"],
    highlights: ["侗族大歌", "蓝染手作", "鼓楼导览", "侗家餐"],
    painPoints: ["民俗表演易表面化", "夜间商业噪声", "手作排班需要预约"],
    resources: ["鼓楼讲解员", "蓝染工坊", "侗家餐厅", "民宿客栈"],
    products: ["蓝染布包", "侗家腌鱼", "糯米酒"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "zhaoxing-drum-tower", name: "五团鼓楼导览", type: "古村导览", duration: "1.5小时", price: 55, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-11:00", desc: "用鼓楼空间理解侗寨组织、公共生活和游客动线。" },
      { id: "zhaoxing-grand-song", name: "侗族大歌小课堂", type: "民俗体验", duration: "1小时", price: 88, bookingRequired: true, tags: ["heritage", "craft"], bestTime: "16:00-17:30", desc: "以小班讲解替代表演式观看，适合研学和家庭客群。" },
      { id: "zhaoxing-indigo", name: "蓝染图案手作", type: "非遗手作", duration: "2小时", price: 128, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "14:00-16:00", desc: "完成可带走作品，并接入工坊文创售卖。" },
      { id: "zhaoxing-rice-fish", name: "稻鱼鸭系统观察", type: "农事体验", duration: "1.5小时", price: 78, bookingRequired: true, tags: ["farming", "nature"], bestTime: "夏秋上午", desc: "讲清稻田生态和侗家饮食之间的关系。" },
      { id: "zhaoxing-dong-dinner", name: "侗家长桌饭与糯米酒", type: "乡土风味", duration: "1.5小时", price: 118, bookingRequired: true, tags: ["food", "homestay"], bestTime: "18:00-19:30", desc: "强化夜间消费和住客互动。" },
    ],
  },
  {
    id: "xijiang",
    name: "西江千户苗寨",
    province: "贵州",
    city: "黔东南州雷山县",
    label: "苗寨夜景与非遗体验",
    cover: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "吊脚楼、苗寨夜景、银饰、苗绣、酸汤鱼",
    lat: 26.494,
    lng: 108.174,
    bestSeason: "春秋民俗、暑期研学",
    matchScore: 90,
    capacity: "高",
    stayNights: 1,
    tags: ["heritage", "craft", "food", "commerce"],
    highlights: ["苗绣银饰", "吊脚楼观察", "苗族餐食", "夜景消费"],
    painPoints: ["商业化感强", "深度内容被打卡淹没", "高峰拥堵"],
    resources: ["非遗工坊", "观景台", "民宿群", "餐饮街区"],
    products: ["苗绣饰品", "银饰文创", "酸汤调料"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "xijiang-stilt-house", name: "吊脚楼聚落观察", type: "村落导览", duration: "1小时", price: 45, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:30", desc: "从居住、坡地和商业空间理解苗寨结构。" },
      { id: "xijiang-silver-workshop", name: "苗银锻制体验", type: "非遗手作", duration: "1.5小时", price: 138, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "14:00-16:00", desc: "让游客理解银饰工艺，而不是只购买成品。" },
      { id: "xijiang-miao-embroidery", name: "苗绣纹样采集", type: "非遗手作", duration: "1.5小时", price: 108, bookingRequired: true, tags: ["craft", "heritage"], bestTime: "10:30-12:00", desc: "适合学生做图案、故事和文创设计采样。" },
      { id: "xijiang-sour-soup", name: "酸汤鱼餐桌故事", type: "乡土风味", duration: "1.5小时", price: 118, bookingRequired: true, tags: ["food", "commerce"], bestTime: "18:00-19:30", desc: "把餐饮变成地方发酵、食材和伴手礼的体验。" },
      { id: "xijiang-night-view", name: "苗寨夜景慢游线", type: "夜间体验", duration: "1.5小时", price: 50, bookingRequired: false, tags: ["homestay", "heritage"], bestTime: "20:00-21:30", desc: "为过夜游客提供轻量化夜游和消费节点。" },
    ],
  },
  {
    id: "heshun",
    name: "和顺古镇",
    province: "云南",
    city: "保山市腾冲市",
    label: "侨乡古镇与火山温泉慢游",
    cover: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "侨乡古宅、图书馆、火山石巷、腾冲小吃、温泉",
    lat: 25.016,
    lng: 98.455,
    bestSeason: "秋冬慢游、春季踏青",
    matchScore: 88,
    capacity: "中",
    stayNights: 2,
    tags: ["heritage", "food", "homestay", "fieldwork"],
    highlights: ["侨乡建筑", "古镇图书馆", "腾冲小吃", "温泉旅居"],
    painPoints: ["村镇与城市旅游边界模糊", "慢游产品需要组合", "交通距离较长"],
    resources: ["侨乡老宅", "图书馆", "小吃工坊", "民宿院落"],
    products: ["腾冲饵丝", "火山石文创", "翡翠小件"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "heshun-library", name: "和顺图书馆与侨乡教育", type: "文化导览", duration: "1小时", price: 45, bookingRequired: false, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:30", desc: "从公共文化和侨乡网络理解古镇气质。" },
      { id: "heshun-overseas-house", name: "侨乡老宅口述史", type: "研学访谈", duration: "1.5小时", price: 88, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "10:30-12:00", desc: "将建筑参观升级为家庭迁徙和地方记忆访谈。" },
      { id: "heshun-er-si", name: "腾冲饵丝早餐课", type: "乡土风味", duration: "1小时", price: 58, bookingRequired: true, tags: ["food", "commerce"], bestTime: "08:00-09:30", desc: "把早餐做成低门槛、强地方性的体验。" },
      { id: "heshun-yard-tea", name: "民宿院落茶叙", type: "民宿旅居", duration: "1.5小时", price: 78, bookingRequired: true, tags: ["homestay", "food"], bestTime: "16:00-17:30", desc: "适合慢游游客停留、交流和复盘路线。" },
      { id: "heshun-volcanic-stone", name: "火山石巷道摄影线", type: "摄影采集", duration: "1.5小时", price: 40, bookingRequired: false, tags: ["heritage", "nature"], bestTime: "15:30-17:30", desc: "将古镇材质、街巷和生活场景转化为素材点。" },
    ],
  },
  {
    id: "songyang-yangtang",
    name: "杨家堂村",
    province: "浙江",
    city: "丽水市松阳县",
    label: "夯土古村与山地美学",
    cover: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "夯土民居、山地古道、古树、摄影点、乡建设计",
    lat: 28.461,
    lng: 119.485,
    bestSeason: "春秋摄影、周末慢游",
    matchScore: 90,
    capacity: "低",
    stayNights: 1,
    tags: ["heritage", "nature", "homestay", "resource"],
    highlights: ["传统村落保护", "山地摄影", "民宿改造", "乡建设计"],
    painPoints: ["容量有限", "交通不便", "商业配套弱"],
    resources: ["古民居", "山地步道", "摄影点位", "小型民宿"],
    products: ["松阳茶", "土蜂蜜", "手作陶器"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "yangtang-earth-house", name: "夯土民居保护导览", type: "古村导览", duration: "1.5小时", price: 60, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:30-11:00", desc: "从材料、居住和保护更新看传统村落。" },
      { id: "yangtang-ancient-tree", name: "古树平台摄影点", type: "摄影采集", duration: "1小时", price: 30, bookingRequired: false, tags: ["nature", "heritage"], bestTime: "16:00-17:30", desc: "稳定产出视觉素材，适合摄影和社交传播。" },
      { id: "yangtang-homestay-renovation", name: "民宿改造案例访谈", type: "资源盘活", duration: "1.5小时", price: 90, bookingRequired: true, tags: ["resource", "homestay", "fieldwork"], bestTime: "工作日", desc: "讨论老宅利用、设计边界和村民收益。" },
      { id: "yangtang-tea-trail", name: "山地茶路轻徒步", type: "山野徒步", duration: "2小时", price: 68, bookingRequired: true, tags: ["nature", "farming"], bestTime: "春秋上午", desc: "把茶园、古道和村落生活串成半日线。" },
      { id: "yangtang-local-dinner", name: "松阳山居晚餐", type: "乡土风味", duration: "1.5小时", price: 108, bookingRequired: true, tags: ["food", "homestay"], bestTime: "18:00-19:30", desc: "用本地菜和茶饮提升过夜价值。" },
    ],
  },
  {
    id: "taoping",
    name: "桃坪羌寨",
    province: "四川",
    city: "阿坝州理县",
    label: "羌寨碉楼与山地防御村落",
    cover: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "羌寨碉楼、石砌巷道、山地河谷、羌绣",
    lat: 31.556,
    lng: 103.353,
    bestSeason: "春秋山地游",
    matchScore: 87,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "craft", "nature", "fieldwork"],
    highlights: ["羌寨建筑", "碉楼导览", "羌绣体验", "山地聚落"],
    painPoints: ["灾后保护叙事复杂", "深度导览不足", "游客停留偏短"],
    resources: ["碉楼讲解", "羌绣工坊", "石巷步道", "民俗餐食"],
    products: ["羌绣挂件", "花椒", "山地蜂蜜"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "taoping-watchtower", name: "碉楼与地下水网导览", type: "古村导览", duration: "1.5小时", price: 70, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:30-11:00", desc: "讲清防御、用水和山地聚落智慧。" },
      { id: "taoping-qiang-embroidery", name: "羌绣纹样手作", type: "非遗手作", duration: "2小时", price: 118, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "14:00-16:00", desc: "将纹样故事、手作体验和文创售卖串联。" },
      { id: "taoping-stone-lane", name: "石砌巷道摄影线", type: "摄影采集", duration: "1小时", price: 35, bookingRequired: false, tags: ["heritage", "nature"], bestTime: "16:00-17:30", desc: "适合生成网站和游客分享素材。" },
      { id: "taoping-valley-walk", name: "河谷轻徒步", type: "山野徒步", duration: "2小时", price: 60, bookingRequired: true, tags: ["nature", "fieldwork"], bestTime: "上午", desc: "连接寨子、河谷和山地农业，需做安全提示。" },
      { id: "taoping-qiang-dinner", name: "羌家晚餐与口述故事", type: "乡土风味", duration: "1.5小时", price: 108, bookingRequired: true, tags: ["food", "homestay", "heritage"], bestTime: "18:00-19:30", desc: "为一日游增加过夜理由和文化记忆。" },
    ],
  },
  {
    id: "jiaju",
    name: "甲居藏寨",
    province: "四川",
    city: "甘孜州丹巴县",
    label: "嘉绒藏居与山谷慢游",
    cover: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "藏寨碉房、山谷花田、嘉绒服饰、民宿观景",
    lat: 30.879,
    lng: 101.884,
    bestSeason: "春季梨花、秋季彩林",
    matchScore: 86,
    capacity: "低",
    stayNights: 2,
    tags: ["heritage", "nature", "homestay", "food"],
    highlights: ["藏居建筑", "花田摄影", "山居民宿", "藏餐体验"],
    painPoints: ["路途较远", "高峰观景点拥挤", "预约组织分散"],
    resources: ["藏居民宿", "观景台", "花田", "家庭餐"],
    products: ["青稞制品", "牦牛肉干", "藏式饰品"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "jiaju-tibetan-house", name: "嘉绒藏居建筑导览", type: "民居导览", duration: "1.5小时", price: 70, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:30-11:00", desc: "从色彩、空间和家庭生活理解藏寨建筑。" },
      { id: "jiaju-flower-field", name: "山谷花田摄影线", type: "摄影采集", duration: "2小时", price: 50, bookingRequired: false, tags: ["nature", "heritage"], bestTime: "春季上午或傍晚", desc: "适合慢游和素材采集，需分散高峰人流。" },
      { id: "jiaju-family-dinner", name: "藏家晚餐与青稞体验", type: "乡土风味", duration: "1.5小时", price: 128, bookingRequired: true, tags: ["food", "homestay"], bestTime: "18:00-19:30", desc: "把住在藏寨的价值落到餐食和家庭交流。" },
      { id: "jiaju-view-homestay", name: "观景民宿晨课", type: "民宿旅居", duration: "1小时", price: 88, bookingRequired: true, tags: ["homestay", "nature"], bestTime: "日出前后", desc: "用晨景、早餐和路线复盘提升过夜体验。" },
      { id: "jiaju-product-corner", name: "青稞与牦牛肉伴手礼角", type: "助农展销", duration: "45分钟", price: 30, bookingRequired: false, tags: ["commerce", "food"], bestTime: "离村前", desc: "把伴手礼作为行程结束的自然转化。" },
    ],
  },
  {
    id: "liukeng",
    name: "流坑村",
    province: "江西",
    city: "抚州市乐安县",
    label: "赣派古村与宗族文化",
    cover: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "古街、宗祠、书院、赣派建筑、村史",
    lat: 27.377,
    lng: 115.769,
    bestSeason: "春秋古村研学",
    matchScore: 85,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "fieldwork", "food", "resource"],
    highlights: ["宗祠书院", "古街导览", "赣菜体验", "传统村落保护"],
    painPoints: ["知名度低", "导览内容需要故事化", "住宿接待较弱"],
    resources: ["宗祠空间", "古街院落", "地方餐食", "村史资料"],
    products: ["米酒", "腐竹", "竹木小件"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "liukeng-ancestral-hall", name: "宗祠与书院导览", type: "古村导览", duration: "1.5小时", price: 55, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:30-11:00", desc: "从教育、宗族和公共空间讲清古村价值。" },
      { id: "liukeng-old-street", name: "古街商贸记忆线", type: "村落导览", duration: "1小时", price: 35, bookingRequired: false, tags: ["heritage", "commerce"], bestTime: "10:30-11:30", desc: "把街巷、店铺和地方产品连接。" },
      { id: "liukeng-rice-wine", name: "米酒与腐竹乡味课", type: "乡土风味", duration: "1.5小时", price: 86, bookingRequired: true, tags: ["food", "commerce"], bestTime: "14:00-15:30", desc: "适合低知名度村落用餐食提升记忆点。" },
      { id: "liukeng-yard-reuse", name: "古院落微展陈策划", type: "资源盘活", duration: "2小时", price: 90, bookingRequired: true, tags: ["resource", "fieldwork"], bestTime: "工作日", desc: "帮助运营者把老院落变成研学和小展空间。" },
      { id: "liukeng-night-reading", name: "书院夜读与村史复盘", type: "夜间体验", duration: "1小时", price: 50, bookingRequired: true, tags: ["homestay", "heritage"], bestTime: "19:30-20:30", desc: "为住客提供安静、文化感强的夜间活动。" },
    ],
  },
  {
    id: "qikou",
    name: "碛口古镇",
    province: "山西",
    city: "吕梁市临县",
    label: "黄河商埠与晋商村镇",
    cover: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "黄河古渡、商埠街巷、窑洞民居、晋商院落",
    lat: 37.652,
    lng: 110.775,
    bestSeason: "春秋黄河古镇游",
    matchScore: 84,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "food", "fieldwork", "homestay"],
    highlights: ["黄河古渡", "晋商街巷", "窑洞民宿", "山西面食"],
    painPoints: ["景区化和村民生活关系需处理", "淡季客源不足", "交通衔接不便"],
    resources: ["古街商铺", "窑洞院落", "黄河观景点", "地方餐食"],
    products: ["红枣", "杂粮", "黄河石文创"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "qikou-yellow-river", name: "黄河古渡口导览", type: "历史导览", duration: "1小时", price: 45, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:30", desc: "从河运、商贸和地形理解碛口兴衰。" },
      { id: "qikou-merchant-street", name: "晋商古街观察", type: "古镇导览", duration: "1.5小时", price: 50, bookingRequired: false, tags: ["heritage", "commerce"], bestTime: "10:30-12:00", desc: "把老商铺、院落和今天的消费转化连接起来。" },
      { id: "qikou-cave-house", name: "窑洞民宿体验", type: "民宿旅居", duration: "1.5小时", price: 98, bookingRequired: true, tags: ["homestay", "heritage"], bestTime: "16:00-17:30", desc: "用居住体验讲清黄土建筑和气候适应。" },
      { id: "qikou-noodle-class", name: "山西面食小课", type: "乡土风味", duration: "1.5小时", price: 88, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "适合亲子和团队，结尾可转化杂粮伴手礼。" },
      { id: "qikou-jube-coop", name: "红枣合作社展销点", type: "助农展销", duration: "45分钟", price: 20, bookingRequired: false, tags: ["commerce", "farming"], bestTime: "离镇前", desc: "把红枣、杂粮等产品接入行程结尾。" },
    ],
  },
  {
    id: "cuandixia",
    name: "爨底下村",
    province: "北京",
    city: "门头沟区斋堂镇",
    label: "京西古村与山地院落",
    cover: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "京西古村、四合院落、山地峡谷、周末短途",
    lat: 39.987,
    lng: 115.635,
    bestSeason: "春秋周末、夏季避暑",
    matchScore: 86,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "nature", "food", "homestay"],
    highlights: ["古院落", "京西山路", "民宿短住", "乡村餐食"],
    painPoints: ["周末拥堵", "院落接待差异", "内容容易只剩拍照"],
    resources: ["古院落", "山地步道", "农家餐", "民宿房源"],
    products: ["山楂制品", "杂粮", "京西文创"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "cuandixia-courtyard", name: "京西古院落导览", type: "古村导览", duration: "1小时", price: 50, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:30-11:00", desc: "从院落、山地和商路理解村庄形成。" },
      { id: "cuandixia-hill-walk", name: "峡谷山路轻徒步", type: "山野徒步", duration: "2小时", price: 60, bookingRequired: true, tags: ["nature", "heritage"], bestTime: "上午", desc: "适合近郊一日游，但需明确体力和安全提示。" },
      { id: "cuandixia-farm-lunch", name: "京西农家午餐", type: "乡土风味", duration: "1.5小时", price: 88, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "把餐饮与地方山货、杂粮做成可复购产品。" },
      { id: "cuandixia-homestay-chat", name: "古村民宿主访谈", type: "产业调研", duration: "1小时", price: 70, bookingRequired: true, tags: ["homestay", "fieldwork"], bestTime: "15:00-16:00", desc: "了解近郊民宿客群、定价和淡旺季问题。" },
      { id: "cuandixia-night-yard", name: "院落星空茶话", type: "夜间体验", duration: "1小时", price: 58, bookingRequired: true, tags: ["homestay", "food"], bestTime: "20:00-21:00", desc: "让近郊短途具备过夜理由。" },
    ],
  },
  {
    id: "dafen",
    name: "大芬油画村",
    province: "广东",
    city: "深圳市龙岗区",
    label: "城郊艺术村与创意体验",
    cover: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "油画工作室、街巷画廊、艺术工坊、城郊创意消费",
    lat: 22.606,
    lng: 114.133,
    bestSeason: "全年城市近郊体验",
    matchScore: 82,
    capacity: "高",
    stayNights: 0,
    tags: ["craft", "commerce", "fieldwork", "resource"],
    highlights: ["油画体验", "工作室访谈", "艺术市集", "产业调研"],
    painPoints: ["乡村属性较弱", "艺术消费同质化", "需突出城郊文旅转型"],
    resources: ["画室", "街区空间", "文创店", "展陈空间"],
    products: ["定制油画", "版画文创", "艺术课程"],
    sourceType: "城郊文旅补充样本 / 正式落地需地方文旅核验",
    spots: [
      { id: "dafen-painting-class", name: "油画小幅创作课", type: "艺术手作", duration: "2小时", price: 158, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "14:00-16:00", desc: "适合亲子、学生和城市游客，成品可带走。" },
      { id: "dafen-studio-talk", name: "画师工作室访谈", type: "产业调研", duration: "1小时", price: 80, bookingRequired: true, tags: ["fieldwork", "resource"], bestTime: "工作日", desc: "理解创意产业、订单模式和街区更新。" },
      { id: "dafen-gallery-walk", name: "街巷画廊导览", type: "文化导览", duration: "1小时", price: 40, bookingRequired: false, tags: ["heritage", "commerce"], bestTime: "10:30-12:00", desc: "把街区游逛变成可讲述路线。" },
      { id: "dafen-art-market", name: "艺术市集与文创转化", type: "助农展销", duration: "1小时", price: 30, bookingRequired: false, tags: ["commerce", "craft"], bestTime: "周末下午", desc: "为资源匹配模块提供城郊创意消费样本。" },
      { id: "dafen-community-renewal", name: "城郊更新观察点", type: "资源盘活", duration: "1.5小时", price: 60, bookingRequired: true, tags: ["resource", "fieldwork"], bestTime: "工作日", desc: "讨论空间租赁、产业集聚和公共文化服务。" },
    ],
  },
  {
    id: "caijiawa",
    name: "蔡家洼村",
    province: "北京",
    city: "密云区巨各庄镇",
    label: "近郊农业与亲子采摘",
    cover: "https://images.unsplash.com/photo-1499529112087-3cb3b73cec95?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "现代农业园、采摘温室、亲子农事、乡村市集",
    lat: 40.372,
    lng: 116.982,
    bestSeason: "全年亲子农业、秋季采摘",
    matchScore: 83,
    capacity: "高",
    stayNights: 0,
    tags: ["farming", "food", "commerce", "fieldwork"],
    highlights: ["采摘体验", "农业园研学", "亲子课程", "助农市集"],
    painPoints: ["近郊产品同质化", "天气影响户外体验", "复购机制弱"],
    resources: ["温室大棚", "采摘园", "市集摊位", "研学教室"],
    products: ["密云果蔬", "蜂蜜", "农场礼盒"],
    sourceType: "近郊农业文旅样本 / 正式落地需地方文旅核验",
    spots: [
      { id: "caijiawa-greenhouse", name: "智能温室研学", type: "农事研学", duration: "1.5小时", price: 68, bookingRequired: true, tags: ["farming", "fieldwork"], bestTime: "09:30-11:00", desc: "适合亲子和学生理解设施农业。" },
      { id: "caijiawa-picking", name: "果蔬采摘任务卡", type: "农事体验", duration: "1.5小时", price: 98, bookingRequired: true, tags: ["farming", "food"], bestTime: "上午或下午", desc: "用任务卡和称重结算提升参与感。" },
      { id: "caijiawa-farm-kitchen", name: "田园厨房午餐", type: "乡土风味", duration: "1.5小时", price: 88, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "把采摘成果转化为餐食体验。" },
      { id: "caijiawa-market", name: "周末助农市集", type: "助农展销", duration: "1小时", price: 20, bookingRequired: false, tags: ["commerce", "resource"], bestTime: "周末15:00-17:00", desc: "适合整理成周末体验、助农购买和复购样本。" },
      { id: "caijiawa-coop-talk", name: "合作社运营访谈", type: "产业调研", duration: "1小时", price: 60, bookingRequired: true, tags: ["fieldwork", "resource"], bestTime: "工作日", desc: "让近郊农业不止停留在采摘，而能讲清经营模型。" },
    ],
  },
];

const AdditionalResourceAssets = [
  { id: "sketch-hongcun", type: "写生基地", villageId: "hongcun", title: "南湖写生点位体验时段", owner: "写生基地", currentState: "淡季团队少", fit: ["heritage", "fieldwork", "homestay"], estimateIncome: 2400, risk: "需避开核心拥堵时段", action: "适合接入学生写生、摄影采集和民宿茶叙套餐。" },
  { id: "platform-huangling", type: "民俗平台", villageId: "huangling", title: "晒秋平台体验档期", owner: "村落运营团队", currentState: "季节性强", fit: ["heritage", "craft", "commerce"], estimateIncome: 2800, risk: "雨天体验效果下降", action: "适合开发晒盘布置、摄影路线和特产直播组合。" },
  { id: "field-longji", type: "梯田田块", villageId: "longji-pingan", title: "龙脊梯田农事体验田", owner: "农户小组", currentState: "按农时开放", fit: ["farming", "nature", "food"], estimateIncome: 2200, risk: "田埂安全与作物保护", action: "适合小班预约，搭配竹筒饭和民宿早餐。" },
  { id: "dye-zhaoxing", type: "非遗工坊", villageId: "zhaoxing", title: "侗寨蓝染工坊空档", owner: "蓝染手艺人", currentState: "工作日上午空档", fit: ["craft", "commerce", "heritage"], estimateIncome: 1900, risk: "染料与排水需规范", action: "适合研学团队和亲子小班，成品可成为文创商品。" },
  { id: "silver-xijiang", type: "非遗工坊", villageId: "xijiang", title: "苗银体验课时段", owner: "银饰工坊", currentState: "散客购买多、体验少", fit: ["craft", "commerce", "heritage"], estimateIncome: 2600, risk: "工具安全与师傅排班", action: "适合把购买转化为工艺体验和定制服务。" },
  { id: "yard-heshun", type: "民宿院落", villageId: "heshun", title: "侨乡民宿院落茶叙空间", owner: "民宿经营户", currentState: "下午利用率低", fit: ["homestay", "food", "heritage"], estimateIncome: 1500, risk: "需控制安静氛围", action: "适合接入慢游茶叙、口述史访谈和小型分享会。" },
  { id: "house-yangtang", type: "闲置古民居", villageId: "songyang-yangtang", title: "夯土老屋微展陈空间", owner: "村集体", currentState: "维护成本高", fit: ["resource", "heritage", "fieldwork"], estimateIncome: 1700, risk: "古建安全与消防", action: "适合做传统村落保护课程和小型展陈。" },
  { id: "craft-taoping", type: "非遗工坊", villageId: "taoping", title: "羌绣体验工坊", owner: "羌绣合作社", currentState: "团队预约不足", fit: ["craft", "commerce", "fieldwork"], estimateIncome: 1600, risk: "老师接待能力有限", action: "适合接入小班手作和文创设计课程。" },
  { id: "homestay-jiaju", type: "民宿余房", villageId: "jiaju", title: "观景藏居民宿周中余房", owner: "民宿主", currentState: "周中空房较多", fit: ["homestay", "nature", "food"], estimateIncome: 2500, risk: "交通距离影响入住", action: "适合打包晨景早餐、家庭晚餐和观景路线。" },
  { id: "hall-liukeng", type: "宗祠空间", villageId: "liukeng", title: "宗祠书院研学空间", owner: "村集体", currentState: "展示利用不足", fit: ["heritage", "fieldwork", "resource"], estimateIncome: 1300, risk: "礼俗边界需说明", action: "适合做村史导览、书院夜读和古院落策划。" },
  { id: "cave-qikou", type: "窑洞院落", villageId: "qikou", title: "黄河窑洞民宿体验房", owner: "民宿经营户", currentState: "淡季入住低", fit: ["homestay", "heritage", "food"], estimateIncome: 1800, risk: "冬季供暖与舒适度", action: "适合打包黄河古渡、面食课和夜间茶话。" },
  { id: "courtyard-cuandixia", type: "古院落", villageId: "cuandixia", title: "京西院落团建空间", owner: "村民经营户", currentState: "周末集中、工作日闲置", fit: ["heritage", "food", "homestay"], estimateIncome: 2100, risk: "周末交通拥堵", action: "适合工作日小团队、近郊研学和农家餐组合。" },
  { id: "studio-dafen", type: "艺术工作室", villageId: "dafen", title: "油画工作室体验课档期", owner: "画师工作室", currentState: "体验课转化一般", fit: ["craft", "commerce", "resource"], estimateIncome: 2300, risk: "城郊乡村属性需解释", action: "适合作为城郊文旅和创意产业调研补充样本。" },
  { id: "greenhouse-caijiawa", type: "温室大棚", villageId: "caijiawa", title: "智能温室亲子研学点", owner: "农业合作社", currentState: "平日客流低", fit: ["farming", "fieldwork", "food"], estimateIncome: 1900, risk: "天气和采摘季波动", action: "适合接入采摘任务卡、农场礼盒和复购观察。" },
];

AdditionalVillages.push(
  {
    id: "xunpu",
    name: "蟳埔村",
    province: "福建",
    city: "泉州市丰泽区",
    label: "海丝渔村与簪花民俗体验",
    cover: "https://www.fujian.gov.cn/zwgk/ztzl/sxzygwzxsgzx/sdjj/wvjj/202507/W020250711300963624242.jpg",
    fallbackVisual: "簪花围、蚵壳厝、渔村码头、海丝女俗、海风街巷",
    lat: 24.889,
    lng: 118.676,
    bestSeason: "春秋海风舒适、节假日民俗氛围强",
    matchScore: 93,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "craft", "food", "commerce"],
    highlights: ["簪花围体验", "蚵壳厝导览", "海丝民俗故事", "海鲜风味"],
    painPoints: ["节假日打卡密度高", "村内步行动线需要梳理", "深度内容容易被短视频化覆盖"],
    resources: ["簪花体验店", "蚵壳厝街巷", "渔港小食铺", "海丝民俗讲解点"],
    products: ["簪花摄影", "鱼卷海味", "闽南文创", "海丝伴手礼"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "xunpu-hairpin", name: "簪花围妆造体验", type: "非遗手作", duration: "1.5小时", price: 128, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "10:00-12:00", desc: "把爆款拍照体验延展为服饰、礼俗与海丝文化讲解。" },
      { id: "xunpu-shell-house", name: "蚵壳厝与渔村街巷导览", type: "古村导览", duration: "1小时", price: 45, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:30", desc: "理解海边聚落材料、信俗与家庭空间结构。" },
      { id: "xunpu-seafood-table", name: "渔家小食与海味餐桌课", type: "乡土风味", duration: "1.5小时", price: 96, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "把蚵仔煎、鱼卷和海味伴手礼接入路线结尾。" },
      { id: "xunpu-story-talk", name: "海丝女俗口述小讲堂", type: "民俗体验", duration: "1小时", price: 68, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "15:00-16:00", desc: "适合研学群体理解渔村女性、海洋贸易与日常生活。" },
      { id: "xunpu-dock-walk", name: "码头日落慢行线", type: "夜间体验", duration: "1小时", price: 36, bookingRequired: false, tags: ["heritage", "food"], bestTime: "17:30-18:30", desc: "为短停游客补足从白天体验到傍晚停留的节奏。" },
    ],
  },
  {
    id: "basha",
    name: "岜沙苗寨",
    province: "贵州",
    city: "黔东南州从江县",
    label: "苗寨火枪礼俗与山林文化",
    cover: "https://vodpub6.v.news.cn/yqfbzx-original/20240817/image/cfc8a1bf-44fb-4351-9a45-6c74b6b79cf1.jpg",
    fallbackVisual: "岜沙梯坡、火枪礼俗、镰刀剃头、苗寨古林、木楼坡地",
    lat: 25.763,
    lng: 108.52,
    bestSeason: "春秋气候舒适、暑期适合民族研学",
    matchScore: 91,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "craft", "nature", "fieldwork"],
    highlights: ["火枪礼俗", "苗寨古林", "剃头仪式讲解", "山地村寨观察"],
    painPoints: ["表演化风险高", "交通衔接依赖包车", "安全边界需提前告知"],
    resources: ["礼俗讲解员", "林地步道", "木楼院落", "苗服体验点"],
    products: ["苗绣挂件", "山地米酒", "苗寨摄影路线"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "basha-ritual", name: "岜沙礼俗讲解", type: "民俗体验", duration: "1小时", price: 58, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:30-10:30", desc: "以小班讲解替代单纯看表演，适合研学和深度游。" },
      { id: "basha-forest", name: "古林与寨门步行线", type: "山野徒步", duration: "1.5小时", price: 46, bookingRequired: true, tags: ["nature", "heritage"], bestTime: "10:30-12:00", desc: "连接村寨、山林和礼俗空间，补足生态维度。" },
      { id: "basha-miao-dress", name: "苗服纹样采样", type: "非遗手作", duration: "1.5小时", price: 98, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "14:00-15:30", desc: "适合摄影、设计和民族服饰研究采样。" },
      { id: "basha-family-fire", name: "火塘家访小课", type: "研学访谈", duration: "1小时", price: 72, bookingRequired: true, tags: ["fieldwork", "homestay"], bestTime: "16:00-17:00", desc: "把家庭生活、山地饮食和村规礼俗讲清楚。" },
      { id: "basha-rice-wine", name: "苗寨晚餐与米酒", type: "乡土风味", duration: "1.5小时", price: 108, bookingRequired: true, tags: ["food", "heritage"], bestTime: "18:00-19:30", desc: "让短线游客有留下吃饭和住一晚的理由。" },
    ],
  },
  {
    id: "chengyang-bazhai",
    name: "程阳八寨",
    province: "广西",
    city: "柳州市三江县",
    label: "风雨桥侗寨与鼓楼慢游",
    cover: "https://vodpub6.v.news.cn/yqfbzx-original/20240831/image/a57508d6-2e3e-4797-ba8e-90baacb7a6ae.jpg",
    fallbackVisual: "风雨桥、鼓楼、侗寨水田、木构街巷、侗家歌声",
    lat: 25.757,
    lng: 109.603,
    bestSeason: "春秋侗寨慢游、夏季稻田观景",
    matchScore: 90,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "craft", "food", "homestay"],
    highlights: ["风雨桥导览", "侗族鼓楼", "侗布手作", "侗家餐食"],
    painPoints: ["热门桥位拥挤", "多寨联动内容需要串线", "夜间产品有待细化"],
    resources: ["风雨桥点位", "鼓楼讲解", "侗布工坊", "侗家客栈"],
    products: ["侗布手作", "油茶伴手礼", "鼓楼研学课程"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "chengyang-bridge", name: "风雨桥与木构讲解", type: "古村导览", duration: "1小时", price: 48, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:30", desc: "从桥梁结构、侗寨水系和公共生活切入。" },
      { id: "chengyang-drum", name: "鼓楼空间观察", type: "文化导览", duration: "1小时", price: 42, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "10:30-11:30", desc: "把单点参观升级为村寨治理和礼俗讲解。" },
      { id: "chengyang-oil-tea", name: "侗家油茶体验", type: "乡土风味", duration: "1小时", price: 56, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-12:30", desc: "适合做轻餐体验和地方伴手礼转化。" },
      { id: "chengyang-cloth", name: "侗布纹样手作", type: "非遗手作", duration: "1.5小时", price: 88, bookingRequired: true, tags: ["craft", "commerce"], bestTime: "14:00-15:30", desc: "让侗布体验成为路线中的可参与节点。" },
      { id: "chengyang-night", name: "寨门夜行与客栈茶叙", type: "夜间体验", duration: "1小时", price: 40, bookingRequired: true, tags: ["homestay", "heritage"], bestTime: "19:30-20:30", desc: "补足过夜客群的夜间节奏，不只停留在白天打卡。" },
    ],
  },
  {
    id: "peitian",
    name: "培田古村",
    province: "福建",
    city: "龙岩市连城县",
    label: "客家古村与耕读家风路线",
    cover: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "客家大宅、书院祠堂、古街巷、夯土墙、山间炊烟",
    lat: 25.629,
    lng: 116.842,
    bestSeason: "春秋古村研学、节假日家风体验",
    matchScore: 89,
    capacity: "中",
    stayNights: 1,
    tags: ["heritage", "fieldwork", "food", "homestay"],
    highlights: ["客家古建筑", "家风家训", "古街慢游", "山村餐食"],
    painPoints: ["名气不如热门古村", "讲解需要故事化", "住宿接待能力分散"],
    resources: ["古厝院落", "祠堂书院", "客家餐厅", "村史讲解"],
    products: ["连城地瓜干", "客家米酒", "古村文创"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "peitian-mansion", name: "客家大宅导览", type: "古村导览", duration: "1.5小时", price: 55, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:30", desc: "从院落、礼序和家族空间理解客家古村。" },
      { id: "peitian-clan", name: "家风家训微讲堂", type: "研学访谈", duration: "1小时", price: 62, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "10:30-11:30", desc: "适合大学生研学、家风教育和社会实践使用。" },
      { id: "peitian-hakka-lunch", name: "客家灶台午餐", type: "乡土风味", duration: "1.5小时", price: 88, bookingRequired: true, tags: ["food", "commerce"], bestTime: "11:30-13:00", desc: "用餐食承接古村停留和伴手礼转化。" },
      { id: "peitian-street-walk", name: "古街巷摄影线", type: "摄影采集", duration: "1小时", price: 35, bookingRequired: false, tags: ["heritage", "nature"], bestTime: "16:00-17:00", desc: "适合做官网图片素材和游客分享内容。" },
      { id: "peitian-yard-stay", name: "古厝夜宿茶话", type: "民宿旅居", duration: "1小时", price: 68, bookingRequired: true, tags: ["homestay", "food"], bestTime: "20:00-21:00", desc: "为过夜客群增加安静但有文化感的夜间活动。" },
    ],
  },
  {
    id: "nuodeng",
    name: "诺邓村",
    province: "云南",
    city: "大理州云龙县",
    label: "千年白族古村与火腿盐井文化",
    cover: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "白族山村、石阶巷道、火腿作坊、古盐井、云雾坡地",
    lat: 25.884,
    lng: 99.372,
    bestSeason: "秋冬火腿季、春季山村慢游",
    matchScore: 88,
    capacity: "低",
    stayNights: 2,
    tags: ["heritage", "food", "fieldwork", "homestay"],
    highlights: ["诺邓火腿", "白族古村", "盐井文化", "山地慢游"],
    painPoints: ["交通距离长", "坡地步行对体力有要求", "接待节点较分散"],
    resources: ["火腿作坊", "白族院落", "石阶巷道", "家庭餐桌"],
    products: ["诺邓火腿", "白族乳扇", "山地蜂蜜"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "nuodeng-ham", name: "火腿制作讲解", type: "乡土风味", duration: "1.5小时", price: 96, bookingRequired: true, tags: ["food", "commerce"], bestTime: "10:00-11:30", desc: "把诺邓火腿从购买转化为可学习、可品尝的体验节点。" },
      { id: "nuodeng-salt", name: "古盐井与村史导览", type: "古村导览", duration: "1小时", price: 52, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "09:00-10:00", desc: "从盐路、贸易和山村形成理解村落历史。" },
      { id: "nuodeng-steps", name: "石阶巷道慢游", type: "山村步行", duration: "1小时", price: 36, bookingRequired: false, tags: ["nature", "heritage"], bestTime: "16:00-17:00", desc: "适合慢游旅居群体和图片采集。" },
      { id: "nuodeng-family", name: "白族院落家访", type: "研学访谈", duration: "1小时", price: 68, bookingRequired: true, tags: ["fieldwork", "homestay"], bestTime: "15:00-16:00", desc: "更适合深度体验，不走纯打卡路线。" },
      { id: "nuodeng-night", name: "山村夜宿与复盘", type: "民宿旅居", duration: "1小时", price: 72, bookingRequired: true, tags: ["homestay", "food"], bestTime: "20:00-21:00", desc: "让长路程换来有价值的停留和休息体验。" },
    ],
  },
  {
    id: "dongziguan",
    name: "东梓关村",
    province: "浙江",
    city: "杭州市富阳区",
    label: "江南水岸乡村与乡建更新样本",
    cover: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "白墙新居、富春江边、江南巷道、回迁建筑、乡建样本",
    lat: 30.061,
    lng: 119.961,
    bestSeason: "春秋周末、近郊研学与设计观察",
    matchScore: 87,
    capacity: "中",
    stayNights: 1,
    tags: ["resource", "heritage", "fieldwork", "homestay"],
    highlights: ["乡建样本", "江南水岸", "建筑观察", "近郊慢游"],
    painPoints: ["视觉热点集中", "文化叙事容易被建筑外观替代", "近郊项目复购机制弱"],
    resources: ["乡建点位", "回迁民居", "河岸步道", "社区共享空间"],
    products: ["建筑导览课程", "江南茶点", "近郊文创"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "dongziguan-architecture", name: "乡建建筑导览", type: "资源盘活", duration: "1.5小时", price: 76, bookingRequired: true, tags: ["resource", "fieldwork"], bestTime: "09:30-11:00", desc: "适合设计、建筑和乡村更新方向的调研。" },
      { id: "dongziguan-river", name: "富春江边慢行线", type: "山水慢游", duration: "1小时", price: 28, bookingRequired: false, tags: ["nature", "homestay"], bestTime: "16:30-17:30", desc: "用河岸景观承接近郊游客的停留节奏。" },
      { id: "dongziguan-community", name: "社区共享空间访谈", type: "研学访谈", duration: "1小时", price: 60, bookingRequired: true, tags: ["resource", "fieldwork"], bestTime: "工作日", desc: "把乡建成果和社区真实使用情况一起讲清楚。" },
      { id: "dongziguan-tea", name: "江南茶点小歇", type: "乡土风味", duration: "45分钟", price: 48, bookingRequired: true, tags: ["food", "commerce"], bestTime: "14:30-15:15", desc: "适合轻量化近郊路线的补给节点。" },
      { id: "dongziguan-night", name: "白墙民宿夜住", type: "民宿旅居", duration: "1小时", price: 88, bookingRequired: true, tags: ["homestay", "resource"], bestTime: "20:00-21:00", desc: "让建筑更新样本延展为可体验的住留产品。" },
    ],
  },
  {
    id: "chenjiapu",
    name: "陈家铺村",
    province: "浙江",
    city: "丽水市松阳县",
    label: "山村书店与乡建旅居体验",
    cover: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "悬崖书店、山村云海、夯土老屋、文创空间、茶山步道",
    lat: 28.493,
    lng: 119.382,
    bestSeason: "春秋云海、周末旅居与书店打卡",
    matchScore: 88,
    capacity: "低",
    stayNights: 1,
    tags: ["resource", "homestay", "heritage", "food"],
    highlights: ["先锋书店", "山村文创", "夯土老屋", "旅居慢游"],
    painPoints: ["山路弯多", "热门点位拥挤", "承载能力有限"],
    resources: ["书店空间", "改造老屋", "茶山步道", "山居民宿"],
    products: ["松阳茶", "山村文创", "乡建课程"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "chenjiapu-bookstore", name: "山村书店驻留", type: "文化体验", duration: "1小时", price: 30, bookingRequired: false, tags: ["resource", "heritage"], bestTime: "10:00-11:00", desc: "适合作为慢游路线中的安静停留节点。" },
      { id: "chenjiapu-renovation", name: "老屋改造观察", type: "资源盘活", duration: "1.5小时", price: 82, bookingRequired: true, tags: ["resource", "fieldwork"], bestTime: "14:00-15:30", desc: "从乡建、运营和村民参与角度理解松阳模式。" },
      { id: "chenjiapu-tea", name: "山村茶席", type: "乡土风味", duration: "1小时", price: 58, bookingRequired: true, tags: ["food", "homestay"], bestTime: "15:30-16:30", desc: "用茶饮承接书店与民宿之间的停留节奏。" },
      { id: "chenjiapu-cloud", name: "云海步道摄影线", type: "摄影采集", duration: "1小时", price: 36, bookingRequired: false, tags: ["nature", "heritage"], bestTime: "清晨或傍晚", desc: "适合作官网图像素材和游客社交传播。" },
      { id: "chenjiapu-stay", name: "山居民宿夜谈", type: "民宿旅居", duration: "1小时", price: 72, bookingRequired: true, tags: ["homestay", "resource"], bestTime: "20:00-21:00", desc: "强化旅居感，不让书店只停留在快闪打卡。" },
    ],
  },
  {
    id: "tangan",
    name: "堂安侗寨",
    province: "贵州",
    city: "黔东南州黎平县",
    label: "侗寨梯田与生态村落体验",
    cover: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1300&q=82",
    fallbackVisual: "侗寨梯田、吊脚楼、山雾步道、木构院落、稻田歌声",
    lat: 25.901,
    lng: 109.228,
    bestSeason: "夏秋梯田、春秋慢游",
    matchScore: 89,
    capacity: "低",
    stayNights: 1,
    tags: ["heritage", "nature", "fieldwork", "homestay"],
    highlights: ["梯田步道", "侗寨木构", "山地慢游", "生态观察"],
    painPoints: ["山地路段较多", "天气影响观景", "接待能力有限"],
    resources: ["梯田步道", "侗家客栈", "木构院落", "稻田观察点"],
    products: ["侗家米酒", "手织布包", "稻田摄影路线"],
    sourceType: "公开资料原型化整理 / 正式落地需地方文旅核验",
    spots: [
      { id: "tangan-terrace", name: "梯田慢行线", type: "山野徒步", duration: "1.5小时", price: 42, bookingRequired: true, tags: ["nature", "fieldwork"], bestTime: "08:30-10:00", desc: "适合做生态、景观和村寨关系观察。" },
      { id: "tangan-wood-house", name: "木构村屋导览", type: "古村导览", duration: "1小时", price: 48, bookingRequired: true, tags: ["heritage", "fieldwork"], bestTime: "10:30-11:30", desc: "从吊脚楼和山地聚落讲清侗寨空间。" },
      { id: "tangan-rice", name: "稻田与侗家小食", type: "乡土风味", duration: "1小时", price: 58, bookingRequired: true, tags: ["food", "homestay"], bestTime: "12:00-13:00", desc: "让游客停留在村里吃一顿，而不只路过。" },
      { id: "tangan-talk", name: "侗寨日常访谈", type: "研学访谈", duration: "1小时", price: 62, bookingRequired: true, tags: ["fieldwork", "heritage"], bestTime: "15:00-16:00", desc: "适合大学生和社会实践群体了解真实日常。" },
      { id: "tangan-night", name: "山寨夜宿静听", type: "民宿旅居", duration: "1小时", price: 66, bookingRequired: true, tags: ["homestay", "nature"], bestTime: "19:30-20:30", desc: "用低干扰夜间体验强化山寨旅居氛围。" },
    ],
  }
);

AdditionalResourceAssets.push(
  { id: "xunpu-hairpin-space", type: "民俗体验店", villageId: "xunpu", title: "簪花妆造与讲解组合档期", owner: "簪花体验店", currentState: "拍照转化高、深度讲解弱", fit: ["craft", "commerce", "heritage"], estimateIncome: 2600, risk: "高峰时段排队明显", action: "适合接入海丝女俗讲解和海味伴手礼套餐。" },
  { id: "basha-ritual-space", type: "礼俗讲解点", villageId: "basha", title: "岜沙礼俗小班讲解时段", owner: "村寨讲解员", currentState: "以看为主、参与偏弱", fit: ["heritage", "fieldwork", "nature"], estimateIncome: 1700, risk: "需要清晰安全边界", action: "适合研学团队按预约时段进入，提升深度内容占比。" },
  { id: "chengyang-bridge-space", type: "风雨桥点位", villageId: "chengyang-bazhai", title: "风雨桥讲解与油茶体验组合", owner: "侗寨运营点", currentState: "游客停留短", fit: ["heritage", "food", "homestay"], estimateIncome: 2100, risk: "热门桥位高峰拥挤", action: "适合把桥梁导览、油茶和客栈夜宿打包。" },
  { id: "peitian-clan-space", type: "祠堂书院", villageId: "peitian", title: "客家家风微课堂空间", owner: "村集体", currentState: "研学利用不足", fit: ["heritage", "fieldwork", "resource"], estimateIncome: 1500, risk: "礼序边界需提前说明", action: "适合大学生研学、家风教育和古村保护讨论。" },
  { id: "nuodeng-ham-space", type: "火腿作坊", villageId: "nuodeng", title: "火腿讲解与品尝时段", owner: "家庭作坊", currentState: "购买多、体验少", fit: ["food", "heritage", "homestay"], estimateIncome: 2300, risk: "旺季产能有限", action: "适合把火腿体验串进旅居和伴手礼路线。" },
  { id: "dongziguan-design-space", type: "共享空间", villageId: "dongziguan", title: "乡建案例分享空间", owner: "社区运营方", currentState: "工作日闲置", fit: ["resource", "fieldwork", "homestay"], estimateIncome: 1400, risk: "需明确接待边界", action: "适合设计类调研和近郊研学路线接入。" },
  { id: "chenjiapu-book-space", type: "书店空间", villageId: "chenjiapu", title: "山村书店活动档期", owner: "书店与合作方", currentState: "打卡多、课程少", fit: ["resource", "homestay", "heritage"], estimateIncome: 1800, risk: "高峰容量有限", action: "适合接入夜谈、读书会和乡建分享活动。" },
  { id: "tangan-terrace-space", type: "梯田步道", villageId: "tangan", title: "堂安梯田导览预约", owner: "侗寨向导", currentState: "路线稳定但讲解不足", fit: ["nature", "fieldwork", "heritage"], estimateIncome: 1600, risk: "雨雾天气影响体验", action: "适合做小团深度导览和学生生态观察。" }
);

RuralData.villages = RuralData.villages.map((village) => ({
  ...village,
  spots: ExistingVillageSpots[village.id] || [],
}));

RuralData.villages.push(...AdditionalVillages);
RuralData.resourceAssets.push(...AdditionalResourceAssets);

const VillageLocationDetails = {
  xidi: { address: "安徽省黄山市黟县西递镇西递村", transportNode: "黄山北站约1小时车程，黟县城区约20分钟车程" },
  azheke: { address: "云南省红河州元阳县新街镇阿者科村", transportNode: "元阳新街镇约40分钟山路车程，建议包车或预约接驳" },
  shibadong: { address: "湖南省湘西州花垣县双龙镇十八洞村", transportNode: "花垣县城约45分钟车程，湘西州内需预留山路时间" },
  beigou: { address: "北京市怀柔区渤海镇北沟村", transportNode: "怀柔北站或怀柔城区约40分钟车程，适合自驾/包车" },
  yucun: { address: "浙江省湖州市安吉县天荒坪镇余村", transportNode: "安吉站约50分钟车程，杭州出发约2小时" },
  xiaogang: { address: "安徽省滁州市凤阳县小溪河镇小岗村", transportNode: "凤阳站或蚌埠南站转车，县城约35分钟车程" },
  hongcun: { address: "安徽省黄山市黟县宏村镇宏村", transportNode: "黄山北站约1.5小时车程，黟县城区约20分钟车程" },
  huangling: { address: "江西省上饶市婺源县江湾镇篁岭村", transportNode: "婺源站约45分钟车程，景区段建议预留索道排队时间" },
  "longji-pingan": { address: "广西壮族自治区桂林市龙胜各族自治县龙脊镇平安村", transportNode: "桂林北/桂林西站约2.5小时车程，山路建议包车" },
  zhaoxing: { address: "贵州省黔东南州黎平县肇兴镇肇兴侗寨", transportNode: "从江站约15分钟车程，黎平县城约1小时车程" },
  xijiang: { address: "贵州省黔东南州雷山县西江镇西江千户苗寨", transportNode: "凯里南站约1小时车程，雷山县城约30分钟车程" },
  heshun: { address: "云南省保山市腾冲市和顺镇和顺古镇", transportNode: "腾冲驼峰机场约30分钟车程，腾冲城区约15分钟车程" },
  "songyang-yangtang": { address: "浙江省丽水市松阳县三都乡杨家堂村", transportNode: "松阳县城约35分钟车程，乡道山路需预留缓冲" },
  taoping: { address: "四川省阿坝州理县桃坪镇桃坪羌寨", transportNode: "成都出发约3.5小时车程，理县城区约30分钟车程" },
  jiaju: { address: "四川省甘孜州丹巴县聂呷乡甲居藏寨", transportNode: "丹巴县城约20分钟车程，川西环线建议分段停留" },
  liukeng: { address: "江西省抚州市乐安县牛田镇流坑村", transportNode: "乐安县城约40分钟车程，抚州东站需转乘县域交通" },
  qikou: { address: "山西省吕梁市临县碛口镇碛口古镇", transportNode: "吕梁站约2小时车程，临县县城约1小时车程" },
  cuandixia: { address: "北京市门头沟区斋堂镇爨底下村", transportNode: "北京市区自驾约2小时，周末山路需预留拥堵缓冲" },
  dafen: { address: "广东省深圳市龙岗区布吉街道大芬油画村", transportNode: "深圳地铁3号线大芬站步行可达，适合城市近郊体验" },
  caijiawa: { address: "北京市密云区巨各庄镇蔡家洼村", transportNode: "密云城区约25分钟车程，北京市区约1.5小时车程" },
  xunpu: { address: "福建省泉州市丰泽区东海街道蟳埔村", transportNode: "泉州东站约30分钟车程，市区可直接打车或公交到村口" },
  basha: { address: "贵州省黔东南州从江县丙妹镇岜沙苗寨", transportNode: "从江县城约15分钟车程，高铁到从江站后建议包车前往" },
  "chengyang-bazhai": { address: "广西壮族自治区柳州市三江侗族自治县林溪镇程阳八寨", transportNode: "三江南站约40分钟车程，景区多寨联动建议预留换乘时间" },
  peitian: { address: "福建省龙岩市连城县宣和镇培田村", transportNode: "连城县城约30分钟车程，冠豸山南站转乘更方便" },
  nuodeng: { address: "云南省大理州云龙县诺邓镇诺邓村", transportNode: "云龙县城约20分钟车程，大理出发建议包车或分段中转" },
  dongziguan: { address: "浙江省杭州市富阳区场口镇东梓关村", transportNode: "富阳城区约35分钟车程，杭州主城自驾约1.5小时" },
  chenjiapu: { address: "浙江省丽水市松阳县四都乡陈家铺村", transportNode: "松阳县城约45分钟山路车程，建议预留转弯缓冲时间" },
  tangan: { address: "贵州省黔东南州黎平县肇兴镇堂安侗寨", transportNode: "从肇兴侗寨继续上山约25分钟车程，适合与肇兴联动停留" },
};

const VillageCoverAssets = {
  xidi: {
    cover: "./assets/village-covers/xidi.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：西递美景",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/rxhmxjgn2022/anhui/detail/2845.html",
  },
  hongcun: {
    cover: "./assets/village-covers/hongcun.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：宏村夏景",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/rxhmxjgn2022/anhui/detail/2845.html",
  },
  azheke: {
    cover: "./assets/village-covers/azheke.png",
    coverSource: "文化和旅游部乡村旅游线路专题：阿者科传统村落",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/mmyghcyt2023/dcxc/detail/5021.html",
  },
  shibadong: {
    cover: "./assets/village-covers/shibadong.jpg",
    coverSource: "新华网：雨后的十八洞村",
    coverSourceUrl: "https://www.news.cn/local/20241126/2d7b1af4e8014da28d15893eb2b32e8a/c.html",
  },
  beigou: {
    cover: "./assets/village-covers/beigou.jpeg",
    coverSource: "中国日报网：怀柔北沟村文旅报道",
    coverSourceUrl: "https://cn.chinadaily.com.cn/a/202410/18/WS6711c29da310b59111d9e8a4.html",
  },
  yucun: {
    cover: "./assets/village-covers/yucun.jpg",
    coverSource: "新华网：安吉县余村景色",
    coverSourceUrl: "https://www.news.cn/photo/20250807/24221dc884a844529999f7cfefeb6e00/c.html",
  },
  xiaogang: {
    cover: "./assets/village-covers/xiaogang.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：小岗村",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/csxz2022/anhui/detail_g7yU_715/4699.html",
  },
  huangling: {
    cover: "./assets/village-covers/huangling.jpg",
    coverSource: "新华网：婺源篁岭古村晒秋景观",
    coverSourceUrl: "https://www.news.cn/20241208/69ad6fdf9b10488b8d47e25efa16ad61/c.html",
  },
  "longji-pingan": {
    cover: "./assets/village-covers/longji-pingan.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：龙胜梯田",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/guangxi_detail/370.html",
  },
  zhaoxing: {
    cover: "./assets/village-covers/zhaoxing.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：肇兴侗寨",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/xczgshsh2023/syxj/detail_shi/3822.html",
  },
  xijiang: {
    cover: "./assets/village-covers/xijiang.png",
    coverSource: "文化和旅游部乡村旅游线路专题：西江千户苗寨",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/xcss2024_xcygj/guizhou/detail/7182.html",
  },
  heshun: {
    cover: "./assets/village-covers/heshun.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：腾冲和顺古镇景区",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/csxz2022/yunnan/detail_g7yU_728/4434.html",
  },
  "songyang-yangtang": {
    cover: "./assets/village-covers/songyang-yangtang.jpg",
    coverSource: "新华网：浙江省松阳县三都乡杨家堂村",
    coverSourceUrl: "https://www.news.cn/photo/2022-08/25/c_1128948302.htm",
  },
  taoping: {
    cover: "./assets/village-covers/taoping.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：桃坪羌寨",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/xcss2024_xcygj/sichuan/detail/7181.html",
  },
  jiaju: {
    cover: "./assets/village-covers/jiaju.jpg",
    coverSource: "环球网转载新华社：丹巴甲居藏寨",
    coverSourceUrl: "https://look.huanqiu.com/article/9CaKrnKnbUK",
  },
  liukeng: {
    cover: "./assets/village-covers/liukeng.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：流坑古村",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/xcszbwg2022/jiangxi/detail/2038.html",
  },
  qikou: {
    cover: "./assets/village-covers/qikou.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：碛口李家山村",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/sx_detail/481.html",
  },
  cuandixia: {
    cover: "./assets/village-covers/cuandixia.jpg",
    coverSource: "文化和旅游部乡村旅游线路专题：爨柏景区/爨底下村",
    coverSourceUrl: "https://zhuanti.mct.gov.cn/rxhmxjgn2022/beijing/detail_g7yU_505/3481.html",
  },
  dafen: {
    cover: "./assets/village-covers/dafen.jpg",
    coverSource: "人民日报：深圳大芬油画村赵小勇工作室",
    coverSourceUrl: "https://paper.people.com.cn/rmrb/html/2024-08/09/nw.D110000renmrb_20240809_2-17.htm",
  },
  caijiawa: {
    cover: "./assets/village-covers/caijiawa.jpg",
    coverSource: "北京旅游网资源库：蔡家洼玫瑰情园",
    coverSourceUrl: "https://s.visitbeijing.com.cn/gallery/6630",
  },
  xunpu: {
    coverSource: "福建省人民政府：泉州蟳埔 风染簪花香 海韵越千年",
    coverSourceUrl: "https://www.fj.gov.cn/zwgk/ztzl/sxzygwzxsgzx/sdjj/wvjj/202507/t20250711_6966218.htm",
  },
  basha: {
    coverSource: "新华网：文化中国行·传统村落人文影像志｜岜沙村：“最后的枪手部落”",
    coverSourceUrl: "https://www.news.cn/photo/20240817/e60cbf0cc06d426eb576ddeb7d8f05c0/c.html",
  },
  "chengyang-bazhai": {
    coverSource: "新华网：文旅新探丨广西三江：“活着”的侗寨",
    coverSourceUrl: "https://www.news.cn/20240831/2e7d472fe9154c14ac8be068757bb226/c.html",
  },
  peitian: {
    cover: "./assets/village-covers/peitian.jpg",
    coverSource: "光明网：福建连城 培田古村 耕读传家",
    coverSourceUrl: "https://news.gmw.cn/2024-03/24/content_37221120.htm",
  },
  nuodeng: {
    cover: "./assets/village-covers/nuodeng.jpg",
    coverSource: "云南乡村振兴：云南大理诺邓古村 千年盐韵绘就文旅新画卷",
    coverSourceUrl: "https://www.ynxc.gov.cn/html/2025/whxdfocus_0417/3022971.html",
  },
  dongziguan: {
    cover: "./assets/village-covers/dongziguan.jpg",
    coverSource: "杭州职业技术学院：富阳东梓关村 杭州市首批“杭派民居”示范村",
    coverSourceUrl: "https://xczx.hzpt.edu.cn/77/ec/c2452a96236/page.htm",
  },
  chenjiapu: {
    cover: "./assets/village-covers/chenjiapu.jpg",
    coverSource: "人民日报客户端：“浙”里传统古村落|松阳陈家铺村：雾罩山野有书香",
    coverSourceUrl: "https://www.peopleapp.com/column/30039055411-500000639802",
  },
  tangan: {
    cover: "./assets/village-covers/tangan.png",
    coverSource: "动静新闻：“夏”一站贵州丨贵州黎平：侗乡古寨好风光",
    coverSourceUrl: "https://movement.gzstv.com/news/detail/ljZJv/",
  },
};

RuralData.villages = RuralData.villages.map((village) => ({
  ...village,
  address: village.address || VillageLocationDetails[village.id]?.address || `${village.province}${village.city}${village.name}`,
  transportNode: village.transportNode || VillageLocationDetails[village.id]?.transportNode || "正式出发前建议使用高德地图核验交通节点",
  ...(VillageCoverAssets[village.id] || {}),
}));
RuralData.meta.catalogScale = {
  villages: RuralData.villages.length,
  spots: RuralData.villages.reduce((sum, village) => sum + (village.spots || []).length, 0),
  resources: RuralData.resourceAssets.length,
};

if (typeof window !== "undefined") {
  window.RuralData = RuralData;
}

if (typeof module !== "undefined") {
  module.exports = RuralData;
}
